# Generated by Django 4.1.2 on 2022-10-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gid', models.CharField(default='G-000BC00', max_length=50)),
                ('password', models.CharField(default='000000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('father_name', models.CharField(max_length=50)),
                ('father_contact', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=50)),
                ('course_enrolled', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('x_percent', models.CharField(max_length=10)),
                ('x_year', models.CharField(max_length=10)),
                ('x_marksheet', models.FileField(default=None, max_length=250, null=True, upload_to='{}marksheets/')),
                ('xii_percent', models.CharField(max_length=10)),
                ('xii_year', models.CharField(max_length=10)),
                ('xii_marksheet', models.FileField(default=None, max_length=250, null=True, upload_to='marksheets/')),
                ('sem_marksheets', models.FileField(default=None, max_length=250, null=True, upload_to='marksheets/')),
                ('img', models.ImageField(upload_to='image/')),
                ('resume', models.FileField(upload_to='resume/')),
                ('sign', models.FileField(upload_to='sign/')),
            ],
        ),
    ]
