# Generated by Django 4.1.2 on 2022-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=9)),
                ('contact_no', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=25)),
                ('father_contact_no', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('personal_email', models.CharField(default='-', max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=9)),
                ('contact_no', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=25)),
                ('father_contact_no', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('personal_email', models.EmailField(max_length=50)),
                ('address', models.CharField(default='@address', max_length=200)),
                ('college_name', models.CharField(max_length=50)),
                ('course_enrolled', models.CharField(max_length=50)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('xii', models.FloatField()),
                ('sem1', models.FloatField()),
                ('sem2', models.FloatField()),
                ('sem3', models.FloatField()),
                ('sem4', models.FloatField()),
                ('sem5', models.FloatField()),
                ('sem6', models.FloatField()),
                ('sem7', models.FloatField()),
                ('sem8', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
