# Generated by Django 4.1.2 on 2022-12-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_personal_detail_profile_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(help_text='Format: G-079CS19', max_length=9, verbose_name='GID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('document', models.FileField(upload_to='', verbose_name='Document')),
            ],
        ),
        migrations.DeleteModel(
            name='Personal_Detail',
        ),
        migrations.AlterModelOptions(
            name='profile_detail',
            options={'verbose_name': 'Profile Detail'},
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='college_name',
            field=models.CharField(default='Global Institute Of Technology, Jaipur', max_length=50, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='contact_no',
            field=models.CharField(max_length=10, verbose_name='Contact No.'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='course_enrolled',
            field=models.CharField(default='B. Tech.', max_length=50, verbose_name='Course Enrolled'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='dob',
            field=models.DateField(help_text='yyyy-mm-dd', verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Enrollment No.'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='father_contact_no',
            field=models.CharField(max_length=10, verbose_name='Father Contact No.'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='father_name',
            field=models.CharField(max_length=25, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='gid',
            field=models.CharField(help_text='Format: G-079CS19', max_length=9, verbose_name='GID'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='personal_email',
            field=models.EmailField(max_length=50, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem1',
            field=models.FloatField(blank=True, verbose_name='1st SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem2',
            field=models.FloatField(blank=True, verbose_name='2nd SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem3',
            field=models.FloatField(blank=True, verbose_name='3rd SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem4',
            field=models.FloatField(blank=True, verbose_name='4th SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem5',
            field=models.FloatField(blank=True, verbose_name='5th SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem6',
            field=models.FloatField(blank=True, verbose_name='6th SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem7',
            field=models.FloatField(blank=True, verbose_name='7th SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='sem8',
            field=models.FloatField(blank=True, verbose_name='8th SEMESTER'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='x',
            field=models.FloatField(verbose_name='10th Grade'),
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='xii',
            field=models.FloatField(verbose_name='12th Grade'),
        ),
    ]
