# Generated by Django 4.1.2 on 2022-12-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_student_documents_delete_personal_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Documents',
            new_name='Student_Document',
        ),
        migrations.AlterModelOptions(
            name='student_document',
            options={'verbose_name': 'Studnet Documents'},
        ),
    ]
