# Generated by Django 4.1.2 on 2022-12-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_rename_student_documents_student_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_document',
            options={'verbose_name': 'Student Document'},
        ),
        migrations.AlterField(
            model_name='profile_detail',
            name='gid',
            field=models.CharField(help_text='Format: G-079CS19, G-(last three digits of Roll.No)+ BranchCode + Enrolled year', max_length=9, verbose_name='GID'),
        ),
        migrations.AlterField(
            model_name='student_document',
            name='gid',
            field=models.CharField(help_text='Format: G-079CS19, G-(last three digits of Roll.No)+ BranchCode + Enrolled year', max_length=9, verbose_name='GID'),
        ),
    ]
