# Generated by Django 4.1.2 on 2022-12-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_alter_student_document_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
