# Generated by Django 4.1.2 on 2022-12-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gid', models.CharField(default='G-000BC00', max_length=50)),
                ('password', models.CharField(default='000000', max_length=50)),
            ],
        ),
    ]
