# Generated by Django 4.1.2 on 2022-12-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_document',
            name='document',
            field=models.FileField(upload_to='Documents/', verbose_name='Document'),
        ),
    ]
