# Generated by Django 4.1.2 on 2022-12-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_alter_student_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gid',
            field=models.CharField(max_length=9),
        ),
    ]
