# Generated by Django 4.1.2 on 2022-12-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_alter_student_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
