# Generated by Django 4.1.2 on 2023-01-07 13:52

import Students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_detail',
            name='profile_pic',
            field=models.ImageField(default='https://res.cloudinary.com/dvfzcddm4/image/upload/v1672828031/Icons/gac_s2xeg7.svg', upload_to='ProfilePic/', verbose_name='Profile_pic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, validators=[Students.models.validate_email, Students.models.validate_student]),
        ),
        migrations.AlterField(
            model_name='student_document',
            name='document',
            field=models.FileField(upload_to='https://icedrive.net/r/ZCfFzTd8B2BZbG19VfXZHFTGbZRzPRx3k5ff4CRC', verbose_name='Document'),
        ),
    ]
