# Generated by Django 4.1.2 on 2023-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_profile_detail_profile_pic_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_detail',
            name='profile_pic',
            field=models.ImageField(default='/ProfilePic/demo_diadpf.jpg', upload_to='ProfilePic/', verbose_name='Profile_pic'),
        ),
    ]
