# Generated by Django 4.1.2 on 2023-01-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_alter_profile_detail_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
