# Generated by Django 4.1.2 on 2023-01-07 20:00

import Students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, validators=[Students.models.validate_email, Students.models.validate_student])),
                ('gid', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
