# Generated by Django 4.1.2 on 2023-01-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0016_delete_student_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(help_text='Format: G-079CS19, G-(last three digits of Roll.No)+ BranchCode + Enrolled year', max_length=9, verbose_name='GID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('document', models.FileField(upload_to='Documents/', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Student Document',
            },
        ),
    ]
