# Generated by Django 4.1.2 on 2023-01-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0018_alter_student_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_detail',
            name='profile_pic',
            field=models.ImageField(default='/ProfilePic/demo_diadpf.jpg', upload_to='ProfilePic/'),
        ),
    ]
