# Generated by Django 4.1.2 on 2023-01-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0019_alter_profile_detail_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_detail',
            name='profile_pic',
            field=models.ImageField(upload_to='ProfilePic/'),
        ),
    ]
