# Generated by Django 4.1.7 on 2023-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0021_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gid',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
