# Generated by Django 4.1.7 on 2023-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0022_alter_student_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gid',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
