# Generated by Django 4.1.7 on 2023-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0023_alter_student_gid_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='SECTION', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='semid',
            field=models.IntegerField(choices=[(1, 'Sem1'), (2, 'Sem2'), (3, 'Sem3'), (4, 'Sem4'), (5, 'Sem5'), (6, 'Sem6'), (7, 'Sem7'), (8, 'Sem8')], default=1),
            preserve_default=False,
        ),
    ]
