# Generated by Django 4.1.7 on 2023-05-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0024_student_section_student_semid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_detail',
            name='Aggregate',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Aggregate CGPA'),
            preserve_default=False,
        ),
    ]
