# Generated by Django 4.1.7 on 2023-05-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0025_profile_detail_aggregate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Detail',
        ),
        migrations.DeleteModel(
            name='Student_Document',
        ),
    ]
