# Generated by Django 4.1.2 on 2023-01-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('sem1', 'Sem1'), ('sem2', 'Sem2'), ('sem3', 'Sem3'), ('sem4', 'Sem4'), ('sem5', 'Sem5'), ('sem6', 'Sem6'), ('sem7', 'Sem7'), ('sem8', 'Sem8')], default='SEMESTER', max_length=5)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='SECTION', max_length=1)),
                ('branch_code', models.CharField(choices=[('CS', 'Cs'), ('ME', 'Me'), ('IT', 'It'), ('EC', 'Ec'), ('EE', 'Ee'), ('CE', 'Ce')], default='Branch_Code', max_length=5)),
                ('schedule', models.FileField(upload_to='Schedule-Lectures')),
            ],
        ),
    ]
