# Generated by Django 4.1.2 on 2023-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecture', '0003_schedulelecture_delete_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semid', models.IntegerField(choices=[(1, 'Sem1'), (2, 'Sem2'), (3, 'Sem3'), (4, 'Sem4'), (5, 'Sem5'), (6, 'Sem6'), (7, 'Sem7'), (8, 'Sem8')])),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='SECTION', max_length=1)),
                ('schedule', models.FileField(upload_to='Schedule-Lectures/')),
                ('updateDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleLecture',
        ),
    ]
