# Generated by Django 4.1.2 on 2022-12-24 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Mechanical', 'Mechanical'), ('Electronics', 'Electronics'), ('Civil', 'Civil'), ('Placements', 'Placements')], default='Category', max_length=25),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 24), editable=False),
        ),
    ]
