# Generated by Django 4.1.2 on 2022-12-25 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_template_category_alter_template_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 25), editable=False),
        ),
    ]
