# Generated by Django 4.1.2 on 2023-01-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0011_book_alter_template_date_alter_template_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('teacher-notes', 'Teacher'), ('student-notes', 'Student'), ('web-notes', 'Other')], default='Category', max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='Notes/')),
            ],
        ),
    ]
