# Generated by Django 4.1.2 on 2023-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0014_alter_lecture_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
