# Generated by Django 4.1.7 on 2023-05-07 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0022_alter_template_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 18, 3, 43, 196266, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
