# Generated by Django 4.1.2 on 2023-05-09 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0027_alter_template_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 9, 20, 1, 22, 217815, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
