# Generated by Django 4.1.2 on 2022-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester_wise_subject',
            name='subject_category',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab')], default='Category', max_length=7),
        ),
    ]
