# Generated by Django 4.1.2 on 2022-10-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0002_semester_wise_subject_subject_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
