# Generated by Django 4.1.2 on 2022-11-10 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0003_delete_student_delete_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('All', 'All'), ('CS', 'Cs'), ('ME', 'Me'), ('IT', 'It'), ('EC', 'Ec'), ('EE', 'Ee'), ('CE', 'Ce')], default='Branch_Code', max_length=5)),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=200)),
                ('event', models.CharField(choices=[('Holiday', 'Holiday'), ('Cultural', 'Cultural'), ('Seminar', 'Seminar')], default='Event', max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.date(2022, 11, 11), editable=False),
        ),
    ]
