# Generated by Django 4.1.2 on 2022-12-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0010_alter_assignment_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.FileField(upload_to='Submission/'),
        ),
    ]
