# Generated by Django 4.1.2 on 2022-12-30 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0012_remove_assignment_status_alter_assignment_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
    ]
