# Generated by Django 4.1.7 on 2023-05-06 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0020_alter_assignment_sdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence_Report',
            new_name='AttendenceReport',
        ),
        migrations.RenameModel(
            old_name='Progress_Report',
            new_name='ProgressReport',
        ),
        migrations.RenameField(
            model_name='attendencereport',
            old_name='subject_id',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='progressreport',
            old_name='subject_id',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester_wise_subject',
            name='semester',
        ),
        migrations.AddField(
            model_name='assignment',
            name='semid',
            field=models.IntegerField(choices=[(1, 'Sem1'), (2, 'Sem2'), (3, 'Sem3'), (4, 'Sem4'), (5, 'Sem5'), (6, 'Sem6'), (7, 'Sem7'), (8, 'Sem8')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester_wise_subject',
            name='semid',
            field=models.IntegerField(choices=[(1, 'Sem1'), (2, 'Sem2'), (3, 'Sem3'), (4, 'Sem4'), (5, 'Sem5'), (6, 'Sem6'), (7, 'Sem7'), (8, 'Sem8')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.date(2023, 5, 7), editable=False),
        ),
    ]
