# Generated by Django 4.1.7 on 2023-05-07 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0022_progress_report_delete_progressreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 17, 12, 43, 434308, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
