# Generated by Django 4.1.7 on 2023-05-07 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0023_alter_assignment_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 17, 46, 8, 184589, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
