# Generated by Django 4.1.7 on 2023-05-07 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0024_alter_assignment_sdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress_report',
            options={'verbose_name': 'Progress Report'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 17, 59, 51, 507328, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
