# Generated by Django 4.1.7 on 2023-05-07 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0025_alter_progress_report_options_alter_assignment_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 18, 3, 43, 192274, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
