# Generated by Django 4.1.7 on 2023-05-07 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0026_alter_assignment_sdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(help_text='Format: G-079CS19, G-(last three digits of Roll.No)+ BranchCode + Enrolled year', max_length=9, verbose_name='GID')),
                ('contact_no', models.CharField(max_length=10, verbose_name='Contact No.')),
                ('father_name', models.CharField(max_length=25, verbose_name='Father Name')),
                ('father_contact_no', models.CharField(max_length=10, verbose_name='Father Contact No.')),
                ('dob', models.DateField(help_text='yyyy-mm-dd', verbose_name='DOB')),
                ('gender', models.CharField(max_length=10)),
                ('personal_email', models.EmailField(max_length=50, verbose_name='Personal Email')),
                ('address', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='ProfilePic/')),
                ('section', models.CharField(default='A', max_length=1, verbose_name='Section Name')),
                ('college_name', models.CharField(default='Global Institute Of Technology, Jaipur', max_length=50, verbose_name='College Name')),
                ('course_enrolled', models.CharField(default='B. Tech.', max_length=50, verbose_name='Course Enrolled')),
                ('enrollment_no', models.CharField(blank=True, max_length=50, verbose_name='Enrollment No.')),
                ('x', models.FloatField(verbose_name='10th Grade')),
                ('xii', models.FloatField(verbose_name='12th Grade')),
                ('sem1', models.FloatField(blank=True, verbose_name='1st SEMESTER')),
                ('sem2', models.FloatField(blank=True, verbose_name='2nd SEMESTER')),
                ('sem3', models.FloatField(blank=True, verbose_name='3rd SEMESTER')),
                ('sem4', models.FloatField(blank=True, verbose_name='4th SEMESTER')),
                ('sem5', models.FloatField(blank=True, verbose_name='5th SEMESTER')),
                ('sem6', models.FloatField(blank=True, verbose_name='6th SEMESTER')),
                ('sem7', models.FloatField(blank=True, verbose_name='7th SEMESTER')),
                ('sem8', models.FloatField(blank=True, verbose_name='8th SEMESTER')),
                ('Aggregate', models.FloatField(blank=True, verbose_name='Aggregate CGPA')),
            ],
            options={
                'verbose_name': 'Profile Detail',
            },
        ),
        migrations.CreateModel(
            name='Student_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(help_text='Format: G-079CS19, G-(last three digits of Roll.No)+ BranchCode + Enrolled year', max_length=9, verbose_name='GID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('document', models.FileField(upload_to='Documents/')),
            ],
            options={
                'verbose_name': 'Student Document',
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 19, 34, 8, 351181, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
