# Generated by Django 4.1.2 on 2023-05-09 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0027_profile_detail_student_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=10)),
                ('sid', models.IntegerField()),
                ('current', models.IntegerField()),
                ('required', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AttendenceReport',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 9, 17, 18, 18, 537763, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
