# Generated by Django 4.1.2 on 2023-05-09 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDashboard', '0028_attendencereports_delete_attendencereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 9, 19, 38, 59, 724962, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
