# Generated by Django 4.1.2 on 2023-05-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=9, unique=True)),
                ('totalFee', models.BigIntegerField()),
                ('DueTutionFee', models.BigIntegerField()),
                ('DueDevelopmentFee', models.BigIntegerField()),
                ('DueOtherFee', models.BigIntegerField()),
                ('TotalDueFee', models.BigIntegerField()),
                ('FeeDetail', models.FileField(upload_to='feeDetail/')),
            ],
            options={
                'verbose_name': 'Fee Desk',
            },
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=9, unique=True)),
                ('txnId', models.CharField(max_length=50)),
                ('txnAmt', models.BigIntegerField()),
                ('txnReciept', models.FileField(upload_to='txnReciept/')),
            ],
            options={
                'verbose_name': 'Fee Transactions',
            },
        ),
    ]
