# Generated by Django 4.1.2 on 2022-11-19 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Computer', 'Cs'), ('Mechanical', 'Me'), ('Electronics', 'Ec'), ('Civil', 'Ce'), ('Placements', 'Pl')], default='Category', max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(default=datetime.date(2022, 11, 20), editable=False)),
            ],
        ),
    ]
