# Generated by Django 4.1.2 on 2023-01-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0012_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField(help_text='e.g.:2023 Format - yyyy', max_length=4)),
                ('paper', models.FileField(upload_to='ExamPapers/')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.FilePathField()),
            ],
        ),
    ]
