# Generated by Django 4.1.2 on 2023-01-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0013_exampaper_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
