# Generated by Django 4.1.7 on 2023-05-06 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0017_alter_template_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='year',
            field=models.IntegerField(help_text='e.g.:2023 Format - yyyy'),
        ),
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 7), editable=False),
        ),
    ]
