# Generated by Django 4.1.7 on 2023-05-07 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0021_alter_template_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 17, 59, 51, 511328, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
