# Generated by Django 4.1.2 on 2023-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science & IT', 'Csit'), ('Mechanical Engineering', 'Me'), ('AI & Data Science', 'Aids'), ('Applied Science', 'As'), ('Civil Engineering', 'Ce'), ('Electrical Engineering', 'Ee')], default='Computer Science & IT', max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('research', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('photo', models.ImageField(upload_to='facultyPic')),
            ],
        ),
    ]
